name: Trigger CI

on:
  push:
    branches:
      - main
    paths:
      - 'nexus-argocd/**'

jobs:
  dispatch:
    uses: rodrigomsr2/ci-templates-homelab/.github/workflows/repository-dispatch.yml@main
    with:
      target-repo: ci-homelab
      event-type: nexus-argocd-push
    secrets:
      dispatch-token: ${{ secrets.CI_DISPATCH_TOKEN }}